---
# Deployment and HPA Config
replicas: 2
maxSurge: 1
maxUnavailable: 1
maxReplicas: 7
targetCPUUtilizationPercentage: 50

env:
  - name: VARIABLE1
    value: ONE
  - name: VARIABLE2
    value: TWO

livenessProbe:
  path: /v1/status
  port: 8080
  initialDelaySeconds: 15
  periodSeconds: 30
  timeoutSeconds: 3
  failureThreshold: 3

readinessProbe:
  path: /v1/status
  port: 8080
  initialDelaySeconds: 3
  periodSeconds: 15
  timeoutSeconds: 3
  failureThreshold: 3
